language: node_js

git:
  depth: false
  submodules: false

node_js:
  - '10.0.0'

branches:
  only:
    - master
    - upgrade

before_install:
  - npm install -g npm@latest
  - npm --version
  - git submodule update --init --recursive
  - npm install backend

before_script:
  - npm install -g npm@6.0.0
  - npm install phantomjs-prebuilt@2.1.16
  - npm install -g karma@1.7.1
  - npm install -g coveralls
  - npm i -g angular-cli-ghpages
  - npm install
  - ng build

script:
  - ng test --watch=false

after_success:
  - npm run coveralls
  - ng build --prod --base-href="https://faxad.github.io/cartify/"
  - sudo ngh